spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pictgram
    username: sa
    password:
    #driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/pictgram
    #username: root
    #password: 

  h2:
    console:
      enabled: true
      debug: true
      
image:
  local: false